# Generated by Django 2.1.7 on 2019-09-22 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190917_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aspects',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=50),
        ),
    ]
